version = 0.1

[default.deploy.parameters]
stack_name = "atlas"
resolve_s3 = true
s3_prefix = "atlas"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
